services:
  frankenphp:
    image: registry.cn-hangzhou.aliyuncs.com/jcleng/dunglas-frankenphp
    restart: unless-stopped
    container_name: frankenphp
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "VIDEO_DIR=/app/public/file"
      - "FAV_DATA_DIR=/data"
    # https://localhost:12356/
    ports:
      - "12356:80"
    volumes:
      - player_data:/data
      - .:/app/public
      - ./Caddyfile:/etc/frankenphp/Caddyfile
      - "/home/jcleng/Downloads/mv/:/app/public/file"
      - "/home/jcleng/work/mywork/myartplayer/.vscode/:/app/public/file/vscode/"
volumes:
  player_data:
