services:
  frankenphp:
    image: registry.cn-hangzhou.aliyuncs.com/jcleng/dunglas-frankenphp
    container_name: frankenphp
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "VIDEO_DIR=/app/public/file"
    # https://localhost:12356/
    ports:
      - "12356:443"
    volumes:
      - .:/app/public
      - ./Caddyfile:/etc/frankenphp/Caddyfile
      - "/home/jcleng/Downloads/mv/:/app/public/file"
